#!/bin/bash

# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=24:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=40   # 20 processor core(s) per node X 2 threads per core
#SBATCH --partition=short    # standard node(s)
#SBATCH --job-name="fastqc"
#SBATCH --mail-user=jonathan.koch@usda.gov   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load fastqc/0.12.1

# Replace "input_folder" with the actual path to your folder containing FASTQ files
input_folder="/project/piru_hylaues/KochProjects/alkalibeepopgen/stacks_pipeline/process_radtags_plate2"

# Replace "output_folder" with the desired path for FastQC results
output_folder="/project/piru_hylaues/KochProjects/alkalibeepopgen/stacks_pipeline/fastqc_plate2"

# Create the output folder if it doesn't exist
mkdir -p "$output_folder"

# Run FastQC on all FASTQ files in the input folder
for fastq_file in "$input_folder"/*.fq*; do
    # Check if the file is a regular file
    if [ -f "$fastq_file" ]; then
        # Extract the file name without the path and extension
        base_name=$(basename -s .fq "$fastq_file")

        # Run FastQC on the current FASTQ file
        fastqc "$fastq_file" --outdir="$output_folder"

        # Print a message indicating completion for this file
        echo "FastQC completed for $base_name"
    fi
done
